#!/usr/bin/env python3
"""Turn scripts/dois.txt into refs.bib via DOI content negotiation (Crossref/DataCite), with a disk cache.
Keys are surname+year+firstword; duplicates get a/b/c suffixes."""
import http.client, pathlib, re, sys, time, unicodedata, urllib.request, urllib.error

CACHE = pathlib.Path("refs-cache")
CONTACT = "michaelalfaro@g.ucla.edu"   # public course contact; Crossref polite pool
UA = f"ecology-evolution-color-book/0.1 (mailto:{CONTACT})"
STOP = {"the", "a", "an", "of", "on", "in", "and", "to", "for", "how", "why", "what", "is", "are"}

def _field(entry: str, name: str) -> str:
    m = re.search(name + r"\s*=\s*[{\"](.*?)[}\"]\s*,?\s*\n?", entry, re.I | re.S)
    return m.group(1).strip() if m else ""

def _ascii(s: str) -> str:
    return "".join(c for c in unicodedata.normalize("NFKD", s) if not unicodedata.combining(c))

def make_key(entry: str) -> str:
    author = _field(entry, "author")
    first = author.split(" and ")[0].strip()
    surname = first.split(",")[0] if "," in first else (first.split()[-1] if first else "")
    surname = re.sub(r"[^a-z]", "", _ascii(surname).lower()) or "anon"
    year = re.search(r"\b(1[89]\d\d|20\d\d)\b", _field(entry, "year")) or re.search(r"year\s*=\s*(\d{4})", entry)
    year = year.group(1) if year else "nd"
    words = [re.sub(r"[^a-z]", "", _ascii(w).lower()) for w in _field(entry, "title").split()]
    words = [w for w in words if w and w not in STOP]
    return f"{surname}{year}{words[0] if words else ''}"

def sanitize(entry: str) -> str:
    """Make Crossref BibTeX acceptable to Typst: brace unquoted month abbreviations (month=Sept -> month={Sept})."""
    return re.sub(r"(month\s*=\s*)([A-Za-z]+)", r"\1{\2}", entry)

def rekey(entry: str, key: str) -> str:
    return re.sub(r"^(@\w+\{)[^,]+,", lambda m: m.group(1) + key + ",", entry.strip(), count=1)

def disambiguate(keys: list[str]) -> list[str]:
    seen, out = {}, []
    for k in keys:
        n = seen.get(k, 0)
        out.append(k if n == 0 else f"{k}{chr(ord('a') + n - 1)}")
        seen[k] = n + 1
    return out

def is_usable(entry: str) -> bool:
    """Reject entries Typst cannot parse or that carry no citable metadata (e.g. figure-component DOIs)."""
    return entry.count("{") == entry.count("}") and bool(_field(entry, "title")) and bool(_field(entry, "author") or _field(entry, "editor"))

def fetch(doi: str) -> str | None:
    CACHE.mkdir(exist_ok=True)
    f = CACHE / (re.sub(r"[^A-Za-z0-9]", "_", doi) + ".bib")
    if f.exists(): return f.read_text()
    req = urllib.request.Request("https://doi.org/" + doi, headers={"Accept": "application/x-bibtex", "User-Agent": UA})
    text = None
    for attempt in range(2):                       # one retry for transient network resets
        try:
            with urllib.request.urlopen(req, timeout=30) as r:
                text = r.read().decode("utf-8", errors="replace")
            break
        except (urllib.error.URLError, http.client.HTTPException, OSError, TimeoutError):
            time.sleep(2)
    if text is None: return None
    if not text.lstrip().startswith("@"): return None
    f.write_text(text)
    time.sleep(0.3)
    return text

def main(dois_path="scripts/dois.txt", out="refs.bib", failed="scripts/dois-failed.txt"):
    dois = [d.strip() for d in pathlib.Path(dois_path).read_text().splitlines() if d.strip()]
    entries, bad = [], []
    for i, d in enumerate(dois, 1):
        e = fetch(d)
        if e and not is_usable(e): e = None
        (entries if e else bad).append(e if e else d)
        if i % 25 == 0: print(f"{i}/{len(dois)}", flush=True)
    keys = disambiguate([make_key(e) for e in entries])
    body = "\n\n".join(rekey(sanitize(e), k) for e, k in zip(entries, keys))
    pathlib.Path(out).write_text("% Generated by scripts/fetch_bibtex.py from scripts/dois.txt. Edit keys here only if you also update citations.\n\n" + body + "\n")
    pathlib.Path(failed).write_text("\n".join(bad) + ("\n" if bad else ""))
    print(f"{len(entries)} entries -> {out}; {len(bad)} failed -> {failed}")

if __name__ == "__main__":
    main(*sys.argv[1:])
