#!/usr/bin/env python3
"""Assemble the drafting inputs for one lecture into drafts/source-packs/lecNN.md.
Sources (all read-only, from the EEB 187 course repo): lecture notes, lecture script (if any),
slide deck text + speaker notes with reveal.js markup stripped, the self-assessment review guide
that covers the lecture, the Further Explorations guide, and an image inventory."""
import pathlib, re, sys

COURSE = pathlib.Path("~/Dropbox/git/EEB187-ecology-evolution-color-2026").expanduser()
SA_FOR_LECTURE = {**{n: 1 for n in range(1, 5)}, **{n: 2 for n in range(5, 9)},
                  **{n: 3 for n in range(9, 13)}, **{n: 4 for n in range(13, 17)}}

SPAN = re.compile(r"\[([^\[\]]*?)\]\{[^}]*\}")
HEADING = re.compile(r"^(#{1,6})\s+(.*?)\s*(\{[^}]*\})?\s*$")
FENCE = re.compile(r"^(:{3,})\s*(.*)$")
PAUSE = re.compile(r"^\s*\.\s\.\s\.\s*$")
IMAGE = re.compile(r"!\[([^\]]*)\]\(([^)\s]+)[^)]*\)")
COMMENT = re.compile(r"<!--.*?-->", re.S)
HR = re.compile(r"^-{3,}\s*$")

def strip_spans(s: str) -> str:
    prev = None
    while prev != s:
        prev, s = s, SPAN.sub(r"\1", s)
    return s

def _drop_frontmatter(text: str) -> str:
    if text.startswith("---"):
        end = text.find("\n---", 3)
        if end != -1: return text[end + 4:]
    return text

def strip_reveal(text: str):
    """Return (slides, images). Slides split at level-2 headings; notes divs are captured separately."""
    text = COMMENT.sub("", _drop_frontmatter(text))
    slides, images = [], []
    cur = None
    stack = []            # fence kinds, innermost last
    for raw in text.splitlines():
        line = raw.rstrip()
        m = FENCE.match(line.strip())
        if m:
            if m.group(2).strip():                          # opening fence
                kind = "notes" if ".notes" in m.group(2) else "div"
                stack.append(kind)
            elif stack:                                     # closing fence
                stack.pop()
            continue
        if PAUSE.match(line) or HR.match(line): continue
        for im in IMAGE.finditer(line):
            images.append(f"{im.group(2)} ({im.group(1)})" if im.group(1) else im.group(2))
        line = IMAGE.sub("", line)
        h = HEADING.match(line)
        if h and len(h.group(1)) == 2 and "notes" not in stack:
            cur = {"title": strip_spans(h.group(2)).strip(), "text": "", "notes": ""}
            slides.append(cur); continue
        if cur is None:
            if line.strip(): cur = {"title": "(before first slide)", "text": "", "notes": ""}; slides.append(cur)
            else: continue
        clean = strip_spans(line)
        if "notes" in stack: cur["notes"] += clean + "\n"
        elif clean.strip(): cur["text"] += clean + "\n"
    return slides, images

def _read(p) -> str:
    return p.read_text(errors="ignore") if p and p.exists() else ""

def _first(glob: str):
    hits = sorted(COURSE.glob(glob))
    return hits[0] if hits else None

def build(n: int) -> str:
    nn = f"{n:02d}"
    notes = next((p for p in sorted(COURSE.glob(f"lectures/lec-{nn}-*.qmd")) if "companion" not in p.name), None)
    companion = _first(f"lectures/lec-{nn}-companion.qmd")
    script = _first(f"lectures/slides/lec-{nn}-lecture-script.md")
    deck = _first(f"lectures/slides/lec-{nn}-slides-covered.qmd") or _first(f"lectures/slides/lec-{nn}-slides.qmd")
    fe = _first(f"further-explorations/fe-{nn}-*.qmd")
    sa = SA_FOR_LECTURE.get(n)
    guide = _first(f"self-assessments/sa-{sa:02d}-review-guide.qmd") if sa else None

    out = [f"# Source pack — Lecture {n}", "",
           "Generated by scripts/source_pack.py from the EEB 187 course repo. Inputs for drafting; do not edit by hand.", ""]
    def section(title, path, body):
        out.extend([f"## {title}", f"_Source: {path.relative_to(COURSE) if path else 'none found'}_", "", body.strip() or "(none)", ""])
    section("Lecture notes (learning objectives, outline, annotated bibliography)", notes, _drop_frontmatter(_read(notes)))
    if companion: section("Instructor companion", companion, _drop_frontmatter(_read(companion)))
    if script: section("Lecture script (word-for-word)", script, _read(script))
    slides, images = strip_reveal(_read(deck)) if deck else ([], [])
    body = []
    for s in slides:
        body.append(f"### {s['title']}")
        if s["text"].strip(): body.append(s["text"].rstrip())
        if s["notes"].strip(): body.append("> **Speaker notes:** " + s["notes"].strip().replace("\n", "\n> "))
        body.append("")
    section(f"Slides and speaker notes ({len(slides)} slides)", deck, "\n".join(body))
    section(f"Self-assessment review guide (SA-{sa})" if sa else "Self-assessment review guide", guide, _drop_frontmatter(_read(guide)))
    section("Further Explorations guide", fe, _drop_frontmatter(_read(fe)))
    section("Image inventory (figure candidates; check CREDITS.md before use)", deck, "\n".join(f"- {i}" for i in images))
    return "\n".join(out)

def main(n: str):
    n = int(n)
    dest = pathlib.Path("drafts/source-packs"); dest.mkdir(parents=True, exist_ok=True)
    p = dest / f"lec{n:02d}.md"
    p.write_text(build(n))
    print(f"wrote {p} ({len(p.read_text().split())} words)")

if __name__ == "__main__":
    main(sys.argv[1])
